//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiSqlFormatForm2.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170")]
        public int MaxLineWidth
        {
            get
            {
                return ((int)(this["MaxLineWidth"]));
            }
            set
            {
                this["MaxLineWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandCommaLists
        {
            get
            {
                return ((bool)(this["ExpandCommaLists"]));
            }
            set
            {
                this["ExpandCommaLists"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeywordAlign
        {
            get
            {
                return ((bool)(this["KeywordAlign"]));
            }
            set
            {
                this["KeywordAlign"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandBooleanExpressions
        {
            get
            {
                return ((bool)(this["ExpandBooleanExpressions"]));
            }
            set
            {
                this["ExpandBooleanExpressions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandCaseStatements
        {
            get
            {
                return ((bool)(this["ExpandCaseStatements"]));
            }
            set
            {
                this["ExpandCaseStatements"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExpandBetweenConditions
        {
            get
            {
                return ((bool)(this["ExpandBetweenConditions"]));
            }
            set
            {
                this["ExpandBetweenConditions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExpandInLists
        {
            get
            {
                return ((bool)(this["ExpandInLists"]));
            }
            set
            {
                this["ExpandInLists"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BreakJoinOnSections
        {
            get
            {
                return ((bool)(this["BreakJoinOnSections"]));
            }
            set
            {
                this["BreakJoinOnSections"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UppercaseKeywords
        {
            get
            {
                return ((bool)(this["UppercaseKeywords"]));
            }
            set
            {
                this["UppercaseKeywords"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HTMLColoring
        {
            get
            {
                return ((bool)(this["HTMLColoring"]));
            }
            set
            {
                this["HTMLColoring"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllIndent
        {
            get
            {
                return ((bool)(this["AllIndent"]));
            }
            set
            {
                this["AllIndent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsAlign
        {
            get
            {
                return ((bool)(this["AsAlign"]));
            }
            set
            {
                this["AsAlign"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllUpper
        {
            get
            {
                return ((bool)(this["AllUpper"]));
            }
            set
            {
                this["AllUpper"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int KeywordLengthOfAs
        {
            get
            {
                return ((int)(this["KeywordLengthOfAs"]));
            }
            set
            {
                this["KeywordLengthOfAs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkdefault
        {
            get
            {
                return ((bool)(this["chkdefault"]));
            }
            set
            {
                this["chkdefault"] = value;
            }
        }
    }
}
